// Generated by Release/Core/generate_embedded_core_trust_roots.py.
// Source: Release/Core/config/embedded-core-keyring.json. Do not edit by hand.

import CryptoKit
import Foundation

public struct CoreCatalogTrustRoot: Sendable, Hashable {
    public enum Status: String, Codable, Sendable { case active, next, revoked }

    public let keyID: String
    public let rawPublicKey: Data
    public let status: Status
    public let notBefore: Date
    public let notAfter: Date?

    public init(
        keyID: String,
        rawPublicKey: Data,
        status: Status,
        notBefore: Date,
        notAfter: Date?
    ) {
        self.keyID = keyID
        self.rawPublicKey = rawPublicKey
        self.status = status
        self.notBefore = notBefore
        self.notAfter = notAfter
    }

    public func publicKey() throws -> Curve25519.Signing.PublicKey {
        try Curve25519.Signing.PublicKey(rawRepresentation: rawPublicKey)
    }
}

/// Production roots are generated from the reviewed release manifest. An empty
/// manifest intentionally keeps App and Helper fail-closed before key ceremony.
public enum VelaCoreCatalogTrustRoots {
    public static let version = 1
    public static let all: [CoreCatalogTrustRoot] = []
}
