#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import json
import re
import sys
from datetime import datetime
from pathlib import Path


class TrustRootGenerationError(ValueError):
    pass


def _parse_time(value: object, label: str) -> datetime:
    if not isinstance(value, str) or re.fullmatch(
        r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", value
    ) is None:
        raise TrustRootGenerationError(f"{label} must be canonical UTC")
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def load_manifest(path: Path) -> dict[str, object]:
    if path.is_symlink() or not path.is_file():
        raise TrustRootGenerationError("embedded Core keyring manifest is missing or unsafe")
    if path.stat().st_size > 64 * 1024:
        raise TrustRootGenerationError("embedded Core keyring manifest is too large")
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict) or set(value) != {
        "schemaVersion",
        "keySetVersion",
        "keys",
    }:
        raise TrustRootGenerationError("embedded Core keyring fields differ from schema")
    if value["schemaVersion"] != 1:
        raise TrustRootGenerationError("embedded Core keyring schema version is unsupported")
    version = value["keySetVersion"]
    if not isinstance(version, int) or isinstance(version, bool) or version < 1:
        raise TrustRootGenerationError("embedded Core keyring version is invalid")
    keys = value["keys"]
    if not isinstance(keys, list):
        raise TrustRootGenerationError("embedded Core keyring keys must be an array")
    seen: set[str] = set()
    for item in keys:
        if not isinstance(item, dict) or set(item) != {
            "keyID",
            "algorithm",
            "publicKeyBase64",
            "status",
            "notBefore",
            "notAfter",
        }:
            raise TrustRootGenerationError("embedded Core key item fields differ from schema")
        key_id = item["keyID"]
        if (
            not isinstance(key_id, str)
            or re.fullmatch(r"[A-Za-z0-9._-]{1,128}", key_id) is None
            or key_id in seen
        ):
            raise TrustRootGenerationError("embedded Core key ID is invalid or duplicated")
        if "TEST" in key_id.upper():
            raise TrustRootGenerationError("test Core key ID is forbidden in embedded roots")
        seen.add(key_id)
        if item["algorithm"] != "ed25519" or item["status"] not in {
            "active",
            "next",
            "revoked",
        }:
            raise TrustRootGenerationError("embedded Core key algorithm/status is invalid")
        try:
            raw_key = base64.b64decode(item["publicKeyBase64"], validate=True)
        except (TypeError, ValueError) as error:
            raise TrustRootGenerationError("embedded Core public key is invalid Base64") from error
        if len(raw_key) != 32:
            raise TrustRootGenerationError("embedded Ed25519 public key must be 32 bytes")
        not_before = _parse_time(item["notBefore"], f"key {key_id} notBefore")
        not_after_value = item["notAfter"]
        if not_after_value is not None:
            not_after = _parse_time(not_after_value, f"key {key_id} notAfter")
            if not_after <= not_before:
                raise TrustRootGenerationError("embedded Core key validity window is invalid")
    return value


def render(manifest: dict[str, object]) -> str:
    roots: list[str] = []
    for item in manifest["keys"]:  # type: ignore[index]
        assert isinstance(item, dict)
        not_after = (
            "nil"
            if item["notAfter"] is None
            else f'try! Date.ISO8601FormatStyle().parse("{item["notAfter"]}")'
        )
        roots.append(
            "        CoreCatalogTrustRoot(\n"
            f'            keyID: "{item["keyID"]}",\n'
            f'            rawPublicKey: Data(base64Encoded: "{item["publicKeyBase64"]}")!,\n'
            f'            status: .{item["status"]},\n'
            f'            notBefore: try! Date.ISO8601FormatStyle().parse("{item["notBefore"]}"),\n'
            f"            notAfter: {not_after}\n"
            "        )"
        )
    if roots:
        roots_literal = "[\n" + ",\n".join(roots) + "\n    ]"
    else:
        roots_literal = "[]"
    return f'''// Generated by Release/Core/generate_embedded_core_trust_roots.py.
// Source: Release/Core/config/embedded-core-keyring.json. Do not edit by hand.

import CryptoKit
import Foundation

public struct CoreCatalogTrustRoot: Sendable, Hashable {{
    public enum Status: String, Codable, Sendable {{ case active, next, revoked }}

    public let keyID: String
    public let rawPublicKey: Data
    public let status: Status
    public let notBefore: Date
    public let notAfter: Date?

    public init(
        keyID: String,
        rawPublicKey: Data,
        status: Status,
        notBefore: Date,
        notAfter: Date?
    ) {{
        self.keyID = keyID
        self.rawPublicKey = rawPublicKey
        self.status = status
        self.notBefore = notBefore
        self.notAfter = notAfter
    }}

    public func publicKey() throws -> Curve25519.Signing.PublicKey {{
        try Curve25519.Signing.PublicKey(rawRepresentation: rawPublicKey)
    }}
}}

/// Production roots are generated from the reviewed release manifest. An empty
/// manifest intentionally keeps App and Helper fail-closed before key ceremony.
public enum VelaCoreCatalogTrustRoots {{
    public static let version = {manifest["keySetVersion"]}
    public static let all: [CoreCatalogTrustRoot] = {roots_literal}
}}
'''


def main() -> int:
    default_root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description="Generate or verify embedded Core trust roots")
    parser.add_argument(
        "--manifest",
        default=str(Path(__file__).with_name("config") / "embedded-core-keyring.json"),
    )
    parser.add_argument(
        "--output",
        default=str(default_root / "VelaIPC/CoreCatalogTrust.swift"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        expected = render(load_manifest(Path(args.manifest)))
        output = Path(args.output)
        if args.check:
            if output.is_symlink() or not output.is_file():
                raise TrustRootGenerationError("generated Core trust-root source is missing or unsafe")
            if output.read_text(encoding="utf-8") != expected:
                raise TrustRootGenerationError(
                    "embedded Core trust roots differ from the canonical release manifest"
                )
            print("Embedded Core trust-root source matches the canonical manifest.")
            return 0
        output.write_text(expected, encoding="utf-8")
        print(f"Generated embedded Core trust roots: {output}")
        return 0
    except (OSError, UnicodeError, json.JSONDecodeError, TrustRootGenerationError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
